In [15]:
import tensorflow as tf

!wget --no-check-certificate \
    https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv \
    -O /tmp/daily-min-temperatures.csv

--2020-06-28 11:26:07--  https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67921 (66K) [text/plain]
Saving to: ‘/tmp/daily-min-temperatures.csv’

/tmp/daily-min-temp 100%[===================>]  66.33K  --.-KB/s    in 0.03s   

2020-06-28 11:26:08 (2.58 MB/s) - ‘/tmp/daily-min-temperatures.csv’ saved [67921/67921]



In [16]:
import csv
import numpy as np

time_step = []
temps = []

with open('/tmp/daily-min-temperatures.csv') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    next(reader)
    step=0
    for row in reader:
        temps.append(float(row[1]))
        time_step.append(step)
        step = step + 1

series = np.array(temps)
time = np.array(time_step)
#plt.figure(figsize=(10, 6))
#plot_series(time, series)

In [17]:
series

array([20.7, 17.9, 18.8, ..., 13.5, 15.7, 13. ])

In [18]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    series = tf.expand_dims(series, axis=-1)
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + 1))
    ds = ds.shuffle(shuffle_buffer)
    ds = ds.map(lambda w: (w[:-1], w[1:]))
    return ds.batch(batch_size).prefetch(1)

In [19]:
split_time = 2500
time_train = time[:split_time]
x_train = series[:split_time]
time_valid = time[split_time:]
x_valid = series[split_time:]


# window_size=132
window_size = 30
batch_size = 32
shuffle_buffer_size = 1000
train_set = windowed_dataset(x_train, window_size, batch_size, shuffle_buffer_size)
print(train_set)
print(x_train.shape)

<PrefetchDataset shapes: ((None, None, 1), (None, None, 1)), types: (tf.float64, tf.float64)>
(2500,)


In [41]:
for x,y in train_set:
    print("---")
    print(x.numpy().shape, y.numpy().shape)

---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32, 30, 1)
---
(32, 30, 1) (32,

In [36]:
print(y.shape)
print(x.shape)

(32, 30, 1)
(32, 30, 1)


In [37]:
x

array([[[ 6.3],
        [10.5],
        [ 7.2],
        [ 7.6],
        [10.7],
        [ 7.8],
        [ 9.6],
        [11.4],
        [12.4],
        [ 8.9],
        [13.2],
        [ 8.6],
        [ 6.2],
        [11.4],
        [13.2],
        [14.3],
        [ 7.3],
        [12.9],
        [ 7.8],
        [ 6.2],
        [ 5.6],
        [10. ],
        [13.3],
        [ 8.3],
        [10.2],
        [ 8.6],
        [ 7.3],
        [10.4],
        [11.2],
        [13.2]],

       [[20.1],
        [19.9],
        [22. ],
        [20.5],
        [22.1],
        [20.6],
        [15. ],
        [20.6],
        [21.5],
        [16.2],
        [14.1],
        [14.5],
        [21.1],
        [15.9],
        [15.2],
        [13.1],
        [13.2],
        [12.5],
        [15.2],
        [17.6],
        [15.5],
        [16.7],
        [16.3],
        [15.1],
        [12.7],
        [10. ],
        [11.4],
        [12.6],
        [10.7],
        [10. ]],

       [[13.6],
        [19.5],
    

In [14]:
for i in train_set:
    print(i)

(<tf.Tensor: shape=(32, 30, 1), dtype=float64, numpy=
array([[[14.6],
        [10.4],
        [13.9],
        [11.9],
        [13.5],
        [ 9.8],
        [14. ],
        [21.5],
        [19.5],
        [16.7],
        [19.1],
        [11. ],
        [ 9. ],
        [10. ],
        [14.6],
        [12.5],
        [17.2],
        [19.2],
        [22.2],
        [15.7],
        [14.2],
        [ 9.8],
        [14. ],
        [17.5],
        [20.7],
        [15.6],
        [13.2],
        [14.5],
        [16.8],
        [17.2]],

       [[11.2],
        [11.4],
        [11.8],
        [12.8],
        [11.6],
        [10.6],
        [ 9.8],
        [11.2],
        [ 5.7],
        [ 7.1],
        [ 2.5],
        [ 3.5],
        [ 4.6],
        [11. ],
        [ 5.7],
        [ 7.7],
        [10.4],
        [11.4],
        [ 9.2],
        [ 6.1],
        [ 2.7],
        [ 4.3],
        [ 6.3],
        [ 3.8],
        [ 4.4],
        [ 7.1],
        [ 4.8],
        [ 5.8],
        [ 6.2],
